export const countries = [
    { key: 'AT', value: 'Austria' },
    { key: 'IN', value: 'India' },
    { key: 'AF', value: 'Afghanistan' },
    { key: 'AL', value: 'Albania' },
    { key: 'DE', value: 'Germany' },
    { key: 'AD', value: 'Andorra' },
    { key: 'AO', value: 'Angola' },
    { key: 'AI', value: 'Anguilla' },
    { key: 'AQ', value: 'Antarctica' },
    { key: 'AG', value: 'Antigua and Barbuda' },
    { key: 'AN', value: 'Netherlands Antilles' },
    { key: 'SA', value: 'Saudi Arabia' },
    { key: 'DZ', value: 'Algeria' },
    { key: 'AR', value: 'Argentina' },
    { key: 'AM', value: 'Armenia' },
    { key: 'AW', value: 'Aruba' },
    { key: 'AU', value: 'Australia' },
    { key: 'AZ', value: 'Azerbaijan' },
    { key: 'BE', value: 'Belgium' },
    { key: 'BA', value: 'Bosnia and Herzegovina' },
    { key: 'BS', value: 'Bahamas' },
    { key: 'BD', value: 'Bangladesh' },
    { key: 'BH', value: 'Bahrain' },
    { key: 'BB', value: 'Barbados' },
    { key: 'BZ', value: 'Belize' },
    { key: 'BJ', value: 'Benin' },
    { key: 'BM', value: 'Bermuda' },
    { key: 'BY', value: 'Belarus' },
    { key: 'MM', value: 'Burma' },
    { key: 'BO', value: 'Bolivia' },
    { key: 'BW', value: 'Botswana' },
    { key: 'BR', value: 'Brazil' },
    { key: 'BN', value: 'Brunei' },
    { key: 'BG', value: 'Bulgaria' },
    { key: 'BI', value: 'Burundi' },
    { key: 'BF', value: 'Burkina Faso' },
    { key: 'BT', value: 'Bhutan' },
    { key: 'CV', value: 'Cape Verde' },
    { key: 'CM', value: 'Cameroon' },
    { key: 'KH', value: 'Cambodia' },
    { key: 'CA', value: 'Canada' },
    { key: 'QA', value: 'Qatar' },
    { key: 'KZ', value: 'Kazakhstan' },
    { key: 'TD', value: 'Chad' },
    { key: 'CL', value: 'Chile' },
    { key: 'CN', value: 'China' },
    { key: 'CY', value: 'Cyprus' },
    { key: 'CO', value: 'Colombia' },
    { key: 'KM', value: 'Comoros' },
    { key: 'CG', value: 'Congo-Brazzaville' },
    { key: 'CD', value: 'Congo-Kinshasa' },
    { key: 'KP', value: 'North Korea' },
    { key: 'KR', value: 'South Korea' },
    { key: 'CR', value: 'Costa Rica' },
    { key: 'CI', value: 'Ivory Coast' },
    { key: 'HR', value: 'Croatia' },
    { key: 'CU', value: 'Cuba' },
    { key: 'DK', value: 'Denmark' },
    { key: 'DM', value: 'Dominica' },
    { key: 'EG', value: 'Egypt' },
    { key: 'AE', value: 'United Arab Emirates' },
    { key: 'EC', value: 'Ecuador' },
    { key: 'ER', value: 'Eritrea' },
    { key: 'SK', value: 'Slovakia' },
    { key: 'SI', value: 'Slovenia' },
    { key: 'ES', value: 'Spain' },
    { key: 'EE', value: 'Estonia' },
    { key: 'US', value: 'United States' },
    { key: 'ET', value: 'Ethiopia' },
    { key: 'FO', value: 'Faroe Islands' },
    { key: 'FJ', value: 'Fiji' },
    { key: 'PH', value: 'Philippines' },
    { key: 'FI', value: 'Finland' },
    { key: 'FR', value: 'France' },
    { key: 'GM', value: 'Gambia' },
    { key: 'GA', value: 'Gabon' },
    { key: 'GH', value: 'Ghana' },
    { key: 'GE', value: 'Georgia' },
    { key: 'GS', value: 'South Georgia and the South Sandwich Islands' },
    { key: 'GI', value: 'Gibraltar' },
    { key: 'GR', value: 'Greece' },
    { key: 'GD', value: 'Grenada' },
    { key: 'GL', value: 'Greenland' },
    { key: 'GP', value: 'Guadeloupe' },
    { key: 'GU', value: 'Guam' },
    { key: 'GT', value: 'Guatemala' },
    { key: 'GY', value: 'Guyana' },
    { key: 'GF', value: 'French Guiana' },
    { key: 'GN', value: 'Guinea' },
    { key: 'GQ', value: 'Equatorial Guinea' },
    { key: 'GW', value: 'Guinea-Bissau' },
    { key: 'HT', value: 'Haiti' },
    { key: 'HN', value: 'Honduras' },
    { key: 'HK', value: 'Hong Kong' },
    { key: 'HU', value: 'Hungary' },
    { key: 'YE', value: 'Yemen' },
    { key: 'BV', value: 'Bouvet Island' },
    { key: 'NF', value: 'Norfolk Island' },
    { key: 'CX', value: 'Christmas Island' },
    { key: 'KY', value: 'Cayman Islands' },
    { key: 'CK', value: 'Cook Islands' },
    { key: 'FK', value: 'Falkland Islands' },
    { key: 'HM', value: 'Heard Island and McDonald Islands' },
    { key: 'MH', value: 'Marshall Islands' },
    { key: 'UM', value: 'United States Minor Outlying Islands' },
    { key: 'SB', value: 'Solomon Islands' },
    { key: 'TC', value: 'Turks and Caicos Islands' },
    { key: 'VI', value: 'U.S. Virgin Islands' },
    { key: 'VG', value: 'British Virgin Islands' },
    { key: 'CC', value: 'Cocos Islands' },
    { key: 'ID', value: 'Indonesia' },
    { key: 'IR', value: 'Iran' },
    { key: 'IQ', value: 'Iraq' },
    { key: 'IE', value: 'Ireland' },
    { key: 'IS', value: 'Iceland' },
    { key: 'IL', value: 'Israel' },
    { key: 'IT', value: 'Italy' },
    { key: 'JM', value: 'Jamaica' },
    { key: 'JP', value: 'Japan' },
    { key: 'DJ', value: 'Djibouti' },
    { key: 'JO', value: 'Jordan' },
    { key: 'YU', value: 'Yugoslavia' },
    { key: 'KW', value: 'Kuwait' },
    { key: 'LB', value: 'Lebanon' },
    { key: 'LY', value: 'Libya' },
    { key: 'LA', value: 'Laos' },
    { key: 'LS', value: 'Lesotho' },
    { key: 'LV', value: 'Latvia' },
    { key: 'LR', value: 'Liberia' },
    { key: 'LI', value: 'Liechtenstein' },
    { key: 'LT', value: 'Lithuania' },
    { key: 'LU', value: 'Luxembourg' },
    { key: 'MX', value: 'Mexico' },
    { key: 'MC', value: 'Monaco' },
    { key: 'MO', value: 'Macau' },
    { key: 'MK', value: 'Macedonia' },
    { key: 'MG', value: 'Madagascar' },
    { key: 'MY', value: 'Malaysia' },
    { key: 'MW', value: 'Malawi' },
    { key: 'MV', value: 'Maldives' },
    { key: 'ML', value: 'Mali' },
    { key: 'MT', value: 'Malta' },
    { key: 'MP', value: 'ds' },
    { key: 'MA', value: 'Morocco' },
    { key: 'MQ', value: 'Martinique' },
    { key: 'MU', value: 'Mauritius' },
    { key: 'MR', value: 'Mauritania' },
    { key: 'YT', value: 'Mayotte' },
    { key: 'FM', value: 'Micronesia' },
    { key: 'MZ', value: 'Mozambique' },
    { key: 'MD', value: 'Moldova' },
    { key: 'MN', value: 'Mongolia' },
    { key: 'MS', value: 'Montserrat' },
    { key: 'NE', value: 'Niger' },
    { key: 'NA', value: 'Namibia' },
    { key: 'NR', value: 'Nauru' },
    { key: 'NP', value: 'Nepal' },
    { key: 'NI', value: 'Nicaragua' },
    { key: 'NG', value: 'Nigeria' },
    { key: 'NU', value: 'Niue' },
    { key: 'NO', value: 'Norway' },
    { key: 'NC', value: 'New Caledonia' },
    { key: 'NZ', value: 'New Zealand' },
    { key: 'OM', value: 'Oman' },
    { key: 'NL', value: 'Netherlands' },
    { key: 'PW', value: 'Palau' },
    { key: 'PA', value: 'Panama' },
    { key: 'PG', value: 'Papua New Guinea' },
    { key: 'PK', value: 'Pakistan' },
    { key: 'PY', value: 'Paraguay' },
    { key: 'PE', value: 'Peru' },
    { key: 'PN', value: 'Pitcairn' },
    { key: 'PL', value: 'Poland' },
    { key: 'PF', value: 'French Polynesia' },
    { key: 'PR', value: 'Puerto Rico' },
    { key: 'PT', value: 'Portugal' },
    { key: 'KE', value: 'Kenya' },
    { key: 'KG', value: 'Kyrgyzstan' },
    { key: 'KI', value: 'Kiribati' },
    { key: 'RU', value: 'Russia' },
    { key: 'GB', value: 'United Kingdom' },
    { key: 'CF', value: 'Central African Republic' },
    { key: 'CZ', value: 'Czech Republic' },
    { key: 'DO', value: 'Dominican Republic' },
    { key: 'RE', value: 'Reunion' },
    { key: 'RO', value: 'Romania' },
    { key: 'RW', value: 'Rwanda' },
    { key: 'KN', value: 'Saint Kitts and Nevis' },
    { key: 'SM', value: 'San Marino' },
    { key: 'PM', value: 'Saint Pierre and Miquelon' },
    { key: 'ST', value: 'Sao Tome and Principe' },
    { key: 'VC', value: 'Saint Vincent and the Grenadines' },
    { key: 'SY', value: 'Syria' },
    { key: 'SV', value: 'El Salvador' },
    { key: 'WS', value: 'Samoa' },
    { key: 'ZA', value: 'South Africa' },
    { key: 'AS', value: 'American Samoa' },
    { key: 'SH', value: 'Saint Helena' },
    { key: 'LC', value: 'Saint Lucia' },
    { key: 'EH', value: 'Western Sahara' },
    { key: 'SC', value: 'Seychelles' },
    { key: 'SN', value: 'Senegal' },
    { key: 'SL', value: 'Sierra Leone' },
    { key: 'SG', value: 'Singapore' },
    { key: 'SO', value: 'Somalia' },
    { key: 'LK', value: 'Sri Lanka' },
    { key: 'SE', value: 'Sweden' },
    { key: 'CH', value: 'Switzerland' },
    { key: 'SZ', value: 'Swaziland' },
    { key: 'SD', value: 'Sudan' },
    { key: 'SR', value: 'Suriname' },
    { key: 'SJ', value: 'Svalbard and Jan Mayen' },
    { key: 'TH', value: 'Thailand' },
    { key: 'TW', value: 'Taiwan' },
    { key: 'TJ', value: 'Tajikistan' },
    { key: 'TZ', value: 'Tanzania' },
    { key: 'IO', value: 'British Indian Ocean Territory' },
    { key: 'TF', value: 'French Southern Territories' },
    { key: 'TL', value: 'Timor-Leste' },
    { key: 'TG', value: 'Togo' },
    { key: 'TK', value: 'Tokelau' },
    { key: 'TO', value: 'Tonga' },
    { key: 'TT', value: 'Trinidad and Tobago' },
    { key: 'TN', value: 'Tunisia' },
    { key: 'TM', value: 'Turkmenistan' },
    { key: 'TR', value: 'Turkey' },
    { key: 'TV', value: 'Tuvalu' },
    { key: 'UA', value: 'Ukraine' },
    { key: 'UG', value: 'Uganda' },
    { key: 'UY', value: 'Uruguay' },
    { key: 'UZ', value: 'Uzbekistan' },
    { key: 'VU', value: 'Vanuatu' },
    { key: 'VA', value: 'Vatican City' },
    { key: 'VE', value: 'Venezuela' },
    { key: 'VN', value: 'Vietnam' },
    { key: 'WF', value: 'Wallis and Futuna' },
    { key: 'ZM', value: 'Zambia' },
    { key: 'ZW', value: 'Zimbabwe' },
];
